# This is a basic workflow that is manually triggered

name: build cpp

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_cpp:
    runs-on: ubuntu-latest

    steps:
    - name: ls
      run: ls -la
    
    - uses: actions/checkout@v3
    
    - name: env report
      run: |
        ls -la
        printenv
